README.rst

update links to new links

---

README.rst

fix my dumb <>

---

discord/guild.py

Add humans and bots to Guild.

---

discord/guild.py

versionadded needs to be added here

---

discord/threads.py

finally gonna be able to boot up bots™?

remove unnecessary await

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
README.rst
docs/conf.py

There were a couple different dpy invites, I just replaced them with the Devision invite (server for edpy)

Fix all invites to the Devision server invite

---

discord/ext/commands/bot.py

Previously slash commands would fetch the prefix and prepend this to the fake message content. This is stupid. I instead just made `bot.get_prefix` check if it is a `_FakeSlashMessage` then return `"/"` so the prefix is always `/` when using a slash command.

Fix slash command prefix to /

---

discord/ext/commands/core.py

This PR makes subcommands register in alphabetical order.

Sort subcommand names

---

discord/http.py

Set the user-agent for this project per https://discord.com/developers/docs/reference#user-agent

Set enhanced-discord.py user-agent

---

discord/gateway.py

For unknown reasons, the `KeepAliveHandler` was a thread, which just sleeps and does `run_coroutine_threadsafe`, which seemed kinda dumb to me. This is also the reason for a thread per voice channel, as `KeepAliveHandler` was subclassed for `VoiceKeepAliveHandler`.
This PR turns the thread into an `asyncio.Task`, and just uses `asyncio.wait_for` and `await` for the calls.

Turn `KeepAliveHandler` into an `asyncio.Task`

---

discord/gateway.py
discord/guild.py
discord/http.py
discord/interactions.py
discord/threads.py
discord/webhook/async_.py
discord/webhook/sync.py

This PR adds `Thread.archive(locked=...)`, a shortcut to `Thread.edit(archive=..., locked=...)`. Fixes #112.

Added Thread.archive

---

discord/permissions.py

This PR adds support for the `START_EMBEDDED_ACTIVITIES` permission.

Add support for start_embedded_activities

---

discord/guild.py
discord/member.py
discord/permissions.py
discord/types/member.py

Implements timeout and related permission.
Adds the following:
`Member.timeout_until, Guild.timed_out_members, Permissions.moderate_members` and `Member.edit(timeout_until=...)`

Implement member timeout

---

discord/ui/view.py

This adds the item that was interacted with to the interaction_check making item specific checks easier

Add item to interaction_check

---

discord/emoji.py
discord/partial_emoji.py

Discussed here: https://discord.com/channels/514232441498763279/881248749849026590/936415100653408348
This PR adds (Partial)Emoji.mention to get the render "format"

Add (Partial)Emoji.mention

---

discord/interactions.py
discord/ui/modal.py
discord/ui/text_input.py
docs/api.rst

Adds docs for modals and text input

Add proper documentation for modals

---

discord/ext/commands/core.py

This PR documents the check attributes that were added in [e65415d](https://github.com/iDevision/enhanced-discord.py/commit/e65415d3c8f1ae01f2e5b91dd5f7f24538cfcadd#) also adds one `required_role` for `commands.has_role`.

Document command check attributes

---

docs/whats_new.rst

This adds the check attributes to the changelogs.
Looks like this:

Add check attributes to changelogs

---

discord/asset.py

This PR adds support for animated guild banners.

Add support for animated guild banners

---

discord/webhook/async_.py

Quick fix major error in Interaction methods
